name: "commit-master"

on:
  push:
    branches: 
    - 'master1'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2

    # docker login,设置登陆到华为的swr
    - name: Log in to HuaweiCloud SWR
      uses: huaweicloud/swr-login@v1
      with:
        region: cn-north-4
        access-key-id: ${{ secrets.ACCESSKEY }}
        access-key-secret: ${{ secrets.SECRETACCESSKEY }}

    - name: "build nginx image for linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x"
      uses: huaweicloud/swr-multiplatform-build-action@v1.0.0
      with:
        image_tag: swr.cn-north-4.myhuaweicloud.com/hcloudcli/nginx:nginx-12-v1.0.0.1
        platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
        use_latest_buildx: true
        push: true
        file: ./dockerfiles/Dockerfile-nginx
