name: "commit-master"

on:
  push:
    branches: 
    - 'master1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2
        
    - name: Set up JDK 19 for maven build
      uses: actions/setup-java@v1
      with:
        java-version: 8

    # 完成java项目打包
    - name: build maven project
      run: mvn clean -U package -Dmaven.test.skip 

    # docker login,设置登陆到华为的swr
    - name: Log in to HuaweiCloud SWR
      uses: huaweicloud/swr-login@v1
      with:
        region: cn-north-4
        access-key-id: ${{ secrets.ACCESSKEY }}
        access-key-secret: ${{ secrets.SECRETACCESSKEY }}
    # 设置 docker 环境
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: "build springcloud demo for linux/amd64,linux/arm64/v8,windows/amd64"
      uses: huaweicloud/swr-multiplatform-build-action@v1.0.0
      with:
        image_tag: swr.cn-north-4.myhuaweicloud.com/actions/jdkdemo:jdk19-v1.06.21.01
        platforms: linux/amd64,linux/arm64/v8,windows/amd64
        use_latest_buildx: false
        push: true
        file: ./Dockerfile
